version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17

  build:
    commands:
      - echo "Running Python Program"
      - python pythoncode.py

artifacts:
  files:
    - '**/*'
